# this workflow will run on all pushes.
on:
  push:

name: "push"
jobs:
  # run golangci-lint to lint the golang source code.
  # the configuration is at /.golangci.yml.
  linter:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4.1.3
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.6
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.42.0
          # optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

  # use nancy to scan for vulnerabilities.
  vulnerability_scanner:
    name: Vulnerability scanner
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4.1.3
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.6
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}

      # we cannot use nancy-github-action because it is outdated, so it's better to use the latest
      # docker image for the validation
      -
        name: nancy
        run: go list -json -m all | docker run -i sonatypecommunity/nancy:latest

  # run golang test suite and collect their coverage.
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v4.1.3
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.6
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: Test
        run: go test -v -count=1 ./...
